#!/bin/sh

set -e

if [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
  deb-systemd-helper mask cassandra-pv-archiver-server.service >/dev/null
fi

if [ "$1" = "purge" ]; then
  deb-systemd-helper purge cassandra-pv-archiver-server.service >/dev/null
  deb-systemd-helper unmask cassandra-pv-archiver-server.service >/dev/null
fi
